### ISSUE TITLE
Remove deprecated Merchants API

### ISSUE THREAD

**Issue by gaelsimon** [Woosmap/openapi-specification#113]
### What?

Remove deprecated Merchants API

### Why?

not used anymore

**Comment by sebastienpro** [comment]
I need to remove all the hidden part in the developers doc

**Comment by sebastienpro** [comment]
https://deploy-preview-912--developers-woosmap.netlify.app/ Here is the preview of the dev doc, no changes should be visible because merchants parts was hidden before ( but not removed )
